package com.demo.models;
// Generated Dec 6, 2022, 10:46:20 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "doanky4")
public class Account implements java.io.Serializable {

	private Integer accountid;
	private Accounttype accounttype;
	private Hotel hotel;
	private String accountname;
	private String phone;
	private String email;
	private String username;
	private String password;
	private String avatar;
	private String verifycode;
	private int accountstt;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Account() {
	}

	public Account(Accounttype accounttype, String accountname, String phone, String email, String username,
			String password, String avatar, int accountstt) {
		this.accounttype = accounttype;
		this.accountname = accountname;
		this.phone = phone;
		this.email = email;
		this.username = username;
		this.password = password;
		this.avatar = avatar;
		this.accountstt = accountstt;
	}

	public Account(Accounttype accounttype, Hotel hotel, String accountname, String phone, String email,
			String username, String password, String avatar, String verifycode, int accountstt,
			Set<Reservation> reservations) {
		this.accounttype = accounttype;
		this.hotel = hotel;
		this.accountname = accountname;
		this.phone = phone;
		this.email = email;
		this.username = username;
		this.password = password;
		this.avatar = avatar;
		this.verifycode = verifycode;
		this.accountstt = accountstt;
		this.reservations = reservations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "accountid", unique = true, nullable = false)
	public Integer getAccountid() {
		return this.accountid;
	}

	public void setAccountid(Integer accountid) {
		this.accountid = accountid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accounttypeid", nullable = false)
	public Accounttype getAccounttype() {
		return this.accounttype;
	}

	public void setAccounttype(Accounttype accounttype) {
		this.accounttype = accounttype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hotelid")
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "accountname", nullable = false, length = 100)
	public String getAccountname() {
		return this.accountname;
	}

	public void setAccountname(String accountname) {
		this.accountname = accountname;
	}

	@Column(name = "phone", nullable = false, length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "avatar", nullable = false, length = 50)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "verifycode", length = 50)
	public String getVerifycode() {
		return this.verifycode;
	}

	public void setVerifycode(String verifycode) {
		this.verifycode = verifycode;
	}

	@Column(name = "accountstt", nullable = false)
	public int getAccountstt() {
		return this.accountstt;
	}

	public void setAccountstt(int accountstt) {
		this.accountstt = accountstt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
