package com.demo.models;
// Generated Dec 6, 2022, 10:46:20 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Accounttype generated by hbm2java
 */
@Entity
@Table(name = "accounttype", catalog = "doanky4")
public class Accounttype implements java.io.Serializable {

	private Integer accounttypeid;
	private String accounttypename;
	private Set<Account> accounts = new HashSet<Account>(0);

	public Accounttype() {
	}

	public Accounttype(String accounttypename) {
		this.accounttypename = accounttypename;
	}

	public Accounttype(String accounttypename, Set<Account> accounts) {
		this.accounttypename = accounttypename;
		this.accounts = accounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "accounttypeid", unique = true, nullable = false)
	public Integer getAccounttypeid() {
		return this.accounttypeid;
	}

	public void setAccounttypeid(Integer accounttypeid) {
		this.accounttypeid = accounttypeid;
	}

	@Column(name = "accounttypename", nullable = false, length = 50)
	public String getAccounttypename() {
		return this.accounttypename;
	}

	public void setAccounttypename(String accounttypename) {
		this.accounttypename = accounttypename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accounttype")
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

}
