package com.demo.models;
// Generated Dec 6, 2022, 10:46:20 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Addonservice generated by hbm2java
 */
@Entity
@Table(name = "addonservice", catalog = "doanky4")
public class Addonservice implements java.io.Serializable {

	private Integer addonserviceid;
	private Hotel hotel;
	private String addonservicename;
	private String servicetype;
	private int netprice;
	private int price;
	private int addonservicestt;
	private Set<Reservationaddonservice> reservationaddonservices = new HashSet<Reservationaddonservice>(0);

	public Addonservice() {
	}

	

	public Addonservice(Integer addonserviceid, Hotel hotel, String addonservicename, String servicetype, int netprice,
			int price, int addonservicestt, Set<Reservationaddonservice> reservationaddonservices) {
		super();
		this.addonserviceid = addonserviceid;
		this.hotel = hotel;
		this.addonservicename = addonservicename;
		this.servicetype = servicetype;
		this.netprice = netprice;
		this.price = price;
		this.addonservicestt = addonservicestt;
		this.reservationaddonservices = reservationaddonservices;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "addonserviceid", unique = true, nullable = false)
	public Integer getAddonserviceid() {
		return this.addonserviceid;
	}

	public void setAddonserviceid(Integer addonserviceid) {
		this.addonserviceid = addonserviceid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hotelid", nullable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "addonservicename", nullable = false, length = 100)
	public String getAddonservicename() {
		return this.addonservicename;
	}

	public void setAddonservicename(String addonservicename) {
		this.addonservicename = addonservicename;
	}
	@Column(name = "servicetype", nullable = false, length = 20)
	public String getServicetype() {
		return servicetype;
	}

	public void setServicetype(String servicetype) {
		this.servicetype = servicetype;
	}

	@Column(name = "netprice", nullable = false, precision = 7, scale = 0)
	public int getNetprice() {
		return this.netprice;
	}

	public void setNetprice(int netprice) {
		this.netprice = netprice;
	}

	@Column(name = "price", nullable = false, precision = 7, scale = 0)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "addonservicestt", nullable = false)
	public int getAddonservicestt() {
		return this.addonservicestt;
	}

	public void setAddonservicestt(int addonservicestt) {
		this.addonservicestt = addonservicestt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addonservice")
	public Set<Reservationaddonservice> getReservationaddonservices() {
		return this.reservationaddonservices;
	}

	public void setReservationaddonservices(Set<Reservationaddonservice> reservationaddonservices) {
		this.reservationaddonservices = reservationaddonservices;
	}

}
