package com.demo.models;
// Generated Dec 6, 2022, 10:46:20 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "doanky4")
public class City implements java.io.Serializable {

	private Integer cityid;
	private Province province;
	private String cityname;
	private Set<Ward> wards = new HashSet<Ward>(0);

	public City() {
	}

	public City(Province province, String cityname) {
		this.province = province;
		this.cityname = cityname;
	}

	public City(Province province, String cityname, Set<Ward> wards) {
		this.province = province;
		this.cityname = cityname;
		this.wards = wards;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cityid", unique = true, nullable = false)
	public Integer getCityid() {
		return this.cityid;
	}

	public void setCityid(Integer cityid) {
		this.cityid = cityid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "provinceid", nullable = false)
	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	@Column(name = "cityname", nullable = false, length = 30)
	public String getCityname() {
		return this.cityname;
	}

	public void setCityname(String cityname) {
		this.cityname = cityname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<Ward> getWards() {
		return this.wards;
	}

	public void setWards(Set<Ward> wards) {
		this.wards = wards;
	}

}
