package com.demo.models;
// Generated Dec 6, 2022, 10:46:20 AM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contractinforoomtype generated by hbm2java
 */
@Entity
@Table(name = "contractinforoomtype", catalog = "doanky4")
public class Contractinforoomtype implements java.io.Serializable {

	private ContractinforoomtypeId id;
	private Contractinfo contractinfo;
	private Roomtype roomtype;
	private double hightseasonprice;
	private double lowseasonprice;

	public Contractinforoomtype() {
	}

	public Contractinforoomtype(ContractinforoomtypeId id, Contractinfo contractinfo, Roomtype roomtype,
			double hightseasonprice, double lowseasonprice) {
		this.id = id;
		this.contractinfo = contractinfo;
		this.roomtype = roomtype;
		this.hightseasonprice = hightseasonprice;
		this.lowseasonprice = lowseasonprice;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "contractid", column = @Column(name = "contractid", nullable = false)),
			@AttributeOverride(name = "roomtypeid", column = @Column(name = "roomtypeid", nullable = false)) })
	public ContractinforoomtypeId getId() {
		return this.id;
	}

	public void setId(ContractinforoomtypeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contractid", nullable = false, insertable = false, updatable = false)
	public Contractinfo getContractinfo() {
		return this.contractinfo;
	}

	public void setContractinfo(Contractinfo contractinfo) {
		this.contractinfo = contractinfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roomtypeid", nullable = false, insertable = false, updatable = false)
	public Roomtype getRoomtype() {
		return this.roomtype;
	}

	public void setRoomtype(Roomtype roomtype) {
		this.roomtype = roomtype;
	}

	@Column(name = "hightseasonprice", nullable = false)
	public double getHightseasonprice() {
		return this.hightseasonprice;
	}

	public void setHightseasonprice(double hightseasonprice) {
		this.hightseasonprice = hightseasonprice;
	}

	@Column(name = "lowseasonprice", nullable = false)
	public double getLowseasonprice() {
		return this.lowseasonprice;
	}

	public void setLowseasonprice(double lowseasonprice) {
		this.lowseasonprice = lowseasonprice;
	}

}
