package com.demo.models;
// Generated Dec 21, 2022, 7:09:31 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contractinfo generated by hbm2java
 */
@Entity
@Table(name = "contractinfo", catalog = "doanky4")
public class Contractinfo implements java.io.Serializable {

	private Integer contractid;
	private Hotel hotel;
	private String taxcode;
	private Date fromdate;
	private Date todate;
	private int contractinfostt;
	private String contractname;
	private String address;
	private String email;
	private String phone;
	private String channel;
	private Set<Contractinforoomtype> contractinforoomtypes = new HashSet<Contractinforoomtype>(0);
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Contractinfo() {
	}

	public Contractinfo(Hotel hotel, String taxcode, Date fromdate, Date todate, int contractinfostt,
			String contractname, String address, String email, String phone, String channel) {
		this.hotel = hotel;
		this.taxcode = taxcode;
		this.fromdate = fromdate;
		this.todate = todate;
		this.contractinfostt = contractinfostt;
		this.contractname = contractname;
		this.address = address;
		this.email = email;
		this.phone = phone;
		this.channel = channel;
	}

	public Contractinfo(Hotel hotel, String taxcode, Date fromdate, Date todate, int contractinfostt,
			String contractname, String address, String email, String phone, String channel,
			Set<Contractinforoomtype> contractinforoomtypes, Set<Reservation> reservations) {
		this.hotel = hotel;
		this.taxcode = taxcode;
		this.fromdate = fromdate;
		this.todate = todate;
		this.contractinfostt = contractinfostt;
		this.contractname = contractname;
		this.address = address;
		this.email = email;
		this.phone = phone;
		this.channel = channel;
		this.contractinforoomtypes = contractinforoomtypes;
		this.reservations = reservations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "contractid", unique = true, nullable = false)
	public Integer getContractid() {
		return this.contractid;
	}

	public void setContractid(Integer contractid) {
		this.contractid = contractid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hoteltid", nullable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "taxcode", nullable = false, length = 50)
	public String getTaxcode() {
		return this.taxcode;
	}

	public void setTaxcode(String taxcode) {
		this.taxcode = taxcode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fromdate", nullable = false, length = 10)
	public Date getFromdate() {
		return this.fromdate;
	}

	public void setFromdate(Date fromdate) {
		this.fromdate = fromdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "todate", nullable = false, length = 10)
	public Date getTodate() {
		return this.todate;
	}

	public void setTodate(Date todate) {
		this.todate = todate;
	}

	@Column(name = "contractinfostt", nullable = false)
	public int getContractinfostt() {
		return this.contractinfostt;
	}

	public void setContractinfostt(int contractinfostt) {
		this.contractinfostt = contractinfostt;
	}

	@Column(name = "contractname", nullable = false, length = 200)
	public String getContractname() {
		return this.contractname;
	}

	public void setContractname(String contractname) {
		this.contractname = contractname;
	}

	@Column(name = "address", nullable = false, length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false, length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "channel", nullable = false, length = 100)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contractinfo")
	public Set<Contractinforoomtype> getContractinforoomtypes() {
		return this.contractinforoomtypes;
	}

	public void setContractinforoomtypes(Set<Contractinforoomtype> contractinforoomtypes) {
		this.contractinforoomtypes = contractinforoomtypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contractinfo")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
