package com.demo.models;
// Generated Dec 6, 2022, 10:46:20 AM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContractinforoomtypeId generated by hbm2java
 */
@Embeddable
public class ContractinforoomtypeId implements java.io.Serializable {

	private int contractid;
	private int roomtypeid;

	public ContractinforoomtypeId() {
	}

	public ContractinforoomtypeId(int contractid, int roomtypeid) {
		this.contractid = contractid;
		this.roomtypeid = roomtypeid;
	}

	@Column(name = "contractid", nullable = false)
	public int getContractid() {
		return this.contractid;
	}

	public void setContractid(int contractid) {
		this.contractid = contractid;
	}

	@Column(name = "roomtypeid", nullable = false)
	public int getRoomtypeid() {
		return this.roomtypeid;
	}

	public void setRoomtypeid(int roomtypeid) {
		this.roomtypeid = roomtypeid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContractinforoomtypeId))
			return false;
		ContractinforoomtypeId castOther = (ContractinforoomtypeId) other;

		return (this.getContractid() == castOther.getContractid())
				&& (this.getRoomtypeid() == castOther.getRoomtypeid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getContractid();
		result = 37 * result + this.getRoomtypeid();
		return result;
	}

}
