package com.demo.models;
// Generated Dec 6, 2022, 10:46:20 AM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Hotelimage generated by hbm2java
 */
@Entity
@Table(name = "hotelimage", catalog = "doanky4")
public class Hotelimage implements java.io.Serializable {

	private Integer imagehotelid;
	private Hotel hotel;
	private String hotelimagename;

	public Hotelimage() {
	}

	public Hotelimage(Hotel hotel, String hotelimagename) {
		this.hotel = hotel;
		this.hotelimagename = hotelimagename;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "imagehotelid", unique = true, nullable = false)
	public Integer getImagehotelid() {
		return this.imagehotelid;
	}

	public void setImagehotelid(Integer imagehotelid) {
		this.imagehotelid = imagehotelid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hotelid", nullable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "hotelimagename", nullable = false, length = 50)
	public String getHotelimagename() {
		return this.hotelimagename;
	}

	public void setHotelimagename(String hotelimagename) {
		this.hotelimagename = hotelimagename;
	}

}
