package com.demo.models;
// Generated Dec 6, 2022, 10:46:20 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Policies generated by hbm2java
 */
@Entity
@Table(name = "policies", catalog = "doanky4")
public class Policies implements java.io.Serializable {

	private Integer policiesid;
	private Roomtype roomtype;
	private String policiescontent;
	private String applyfor;
	private Date fromdate;
	private Date todate;
	private int minbeforecheckindate;
	private int maxbeforcheckindate;
	private int refund;
	private int reissue;
	private int policiesstatus;

	public Policies() {
	}

	public Policies(Roomtype roomtype, String policiescontent, String applyfor, Date fromdate, Date todate,
			int minbeforecheckindate, int maxbeforcheckindate, int refund, int reissue, int policiesstatus) {
		this.roomtype = roomtype;
		this.policiescontent = policiescontent;
		this.applyfor = applyfor;
		this.fromdate = fromdate;
		this.todate = todate;
		this.minbeforecheckindate = minbeforecheckindate;
		this.maxbeforcheckindate = maxbeforcheckindate;
		this.refund = refund;
		this.reissue = reissue;
		this.policiesstatus = policiesstatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "policiesid", unique = true, nullable = false)
	public Integer getPoliciesid() {
		return this.policiesid;
	}

	public void setPoliciesid(Integer policiesid) {
		this.policiesid = policiesid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roomstypeid", nullable = false)
	public Roomtype getRoomtype() {
		return this.roomtype;
	}

	public void setRoomtype(Roomtype roomtype) {
		this.roomtype = roomtype;
	}

	@Column(name = "policiescontent", nullable = false, length = 250)
	public String getPoliciescontent() {
		return this.policiescontent;
	}

	public void setPoliciescontent(String policiescontent) {
		this.policiescontent = policiescontent;
	}

	@Column(name = "applyfor", nullable = false, length = 50)
	public String getApplyfor() {
		return this.applyfor;
	}

	public void setApplyfor(String applyfor) {
		this.applyfor = applyfor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fromdate", nullable = false, length = 10)
	public Date getFromdate() {
		return this.fromdate;
	}

	public void setFromdate(Date fromdate) {
		this.fromdate = fromdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "todate", nullable = false, length = 10)
	public Date getTodate() {
		return this.todate;
	}

	public void setTodate(Date todate) {
		this.todate = todate;
	}

	@Column(name = "minbeforecheckindate", nullable = false)
	public int getMinbeforecheckindate() {
		return this.minbeforecheckindate;
	}

	public void setMinbeforecheckindate(int minbeforecheckindate) {
		this.minbeforecheckindate = minbeforecheckindate;
	}

	@Column(name = "maxbeforcheckindate", nullable = false)
	public int getMaxbeforcheckindate() {
		return this.maxbeforcheckindate;
	}

	public void setMaxbeforcheckindate(int maxbeforcheckindate) {
		this.maxbeforcheckindate = maxbeforcheckindate;
	}

	@Column(name = "refund", nullable = false)
	public int getRefund() {
		return this.refund;
	}

	public void setRefund(int refund) {
		this.refund = refund;
	}

	@Column(name = "reissue", nullable = false)
	public int getReissue() {
		return this.reissue;
	}

	public void setReissue(int reissue) {
		this.reissue = reissue;
	}

	@Column(name = "policiesstatus", nullable = false)
	public int getPoliciesstatus() {
		return this.policiesstatus;
	}

	public void setPoliciesstatus(int policiesstatus) {
		this.policiesstatus = policiesstatus;
	}

}
