package com.demo.models;
// Generated Dec 6, 2022, 10:46:20 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservationroomdetails generated by hbm2java
 */
@Entity
@Table(name = "reservationroomdetails", catalog = "doanky4")
public class Reservationroomdetails implements java.io.Serializable {

	private Integer reservationroomdetailsid;
	private Reservation reservation;
	private Rooms rooms;
	private Date checkintime;
	private Date checkouttime;
	private int cusinroom;
	private int latecheckoutid;
	private int reservationroomtypestt;
	private Set<Reservationguestinfo> reservationguestinfos = new HashSet<Reservationguestinfo>(0);
	private Set<Reservationaddonservice> reservationaddonservices = new HashSet<Reservationaddonservice>(0);

	public Reservationroomdetails() {
	}

	public Reservationroomdetails(Reservation reservation, Rooms rooms, int reservationroomtypestt) {
		this.reservation = reservation;
		this.rooms = rooms;
		this.reservationroomtypestt = reservationroomtypestt;
	}

	public Reservationroomdetails(Reservation reservation, Rooms rooms, Date checkintime, Date checkouttime,
			int reservationroomtypestt, Set<Reservationguestinfo> reservationguestinfos,
			Set<Reservationaddonservice> reservationaddonservices) {
		this.reservation = reservation;
		this.rooms = rooms;
		this.checkintime = checkintime;
		this.checkouttime = checkouttime;
		this.reservationroomtypestt = reservationroomtypestt;
		this.reservationguestinfos = reservationguestinfos;
		this.reservationaddonservices = reservationaddonservices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "reservationroomdetailsid", unique = true, nullable = false)
	public Integer getReservationroomdetailsid() {
		return this.reservationroomdetailsid;
	}

	public void setReservationroomdetailsid(Integer reservationroomdetailsid) {
		this.reservationroomdetailsid = reservationroomdetailsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reservationid", nullable = false)
	public Reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(Reservation reservation) {
		this.reservation = reservation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roomid", nullable = false)
	public Rooms getRooms() {
		return this.rooms;
	}

	public void setRooms(Rooms rooms) {
		this.rooms = rooms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checkintime", length = 19)
	public Date getCheckintime() {
		return this.checkintime;
	}

	public void setCheckintime(Date checkintime) {
		this.checkintime = checkintime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checkouttime", length = 19)
	public Date getCheckouttime() {
		return this.checkouttime;
	}

	public void setCheckouttime(Date checkouttime) {
		this.checkouttime = checkouttime;
	}
	@Column(name = "cusinroom", nullable = false)
	public int getCusinroom() {
		return cusinroom;
	}

	public void setCusinroom(int cusinroom) {
		this.cusinroom = cusinroom;
	}
	@Column(name = "latecheckoutid")
	public int getLatecheckoutid() {
		return latecheckoutid;
	}

	public void setLatecheckoutid(int latecheckoutid) {
		this.latecheckoutid = latecheckoutid;
	}

	@Column(name = "reservationroomtypestt", nullable = false)
	public int getReservationroomtypestt() {
		return this.reservationroomtypestt;
	}

	public void setReservationroomtypestt(int reservationroomtypestt) {
		this.reservationroomtypestt = reservationroomtypestt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reservationroomdetails")
	public Set<Reservationguestinfo> getReservationguestinfos() {
		return this.reservationguestinfos;
	}

	public void setReservationguestinfos(Set<Reservationguestinfo> reservationguestinfos) {
		this.reservationguestinfos = reservationguestinfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reservationroomdetails")
	public Set<Reservationaddonservice> getReservationaddonservices() {
		return this.reservationaddonservices;
	}

	public void setReservationaddonservices(Set<Reservationaddonservice> reservationaddonservices) {
		this.reservationaddonservices = reservationaddonservices;
	}

	public Reservationroomdetails(Integer reservationroomdetailsid, Reservation reservation, Rooms rooms,
			Date checkintime, Date checkouttime, int cusinroom, int reservationroomtypestt,
			Set<Reservationguestinfo> reservationguestinfos, Set<Reservationaddonservice> reservationaddonservices) {
		super();
		this.reservationroomdetailsid = reservationroomdetailsid;
		this.reservation = reservation;
		this.rooms = rooms;
		this.checkintime = checkintime;
		this.checkouttime = checkouttime;
		this.cusinroom = cusinroom;
		this.reservationroomtypestt = reservationroomtypestt;
		this.reservationguestinfos = reservationguestinfos;
		this.reservationaddonservices = reservationaddonservices;
	}

	public Reservationroomdetails(Integer reservationroomdetailsid, Reservation reservation, Rooms rooms,
			Date checkintime, Date checkouttime, int cusinroom, int latecheckoutid, int reservationroomtypestt,
			Set<Reservationguestinfo> reservationguestinfos, Set<Reservationaddonservice> reservationaddonservices) {
		super();
		this.reservationroomdetailsid = reservationroomdetailsid;
		this.reservation = reservation;
		this.rooms = rooms;
		this.checkintime = checkintime;
		this.checkouttime = checkouttime;
		this.cusinroom = cusinroom;
		this.latecheckoutid = latecheckoutid;
		this.reservationroomtypestt = reservationroomtypestt;
		this.reservationguestinfos = reservationguestinfos;
		this.reservationaddonservices = reservationaddonservices;
	}
	
	

}
