package com.demo.models;
// Generated Dec 6, 2022, 10:46:20 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservationaddonservice generated by hbm2java
 */
@Entity
@Table(name = "reservationaddonservice", catalog = "doanky4")
public class Reservationaddonservice implements java.io.Serializable {

	private Integer reservationaddonserviceid;
	private Addonservice addonservice;
	private Reservationroomdetails reservationroomdetails;
	private Date createday;
	private double price;
	private int quantity;
	private double amount;
	private Date paymentdate;
	private String paymentchannel;
	private int latecheckoutid;
	private int paymentstt;

	public Reservationaddonservice() {
	}

	public Reservationaddonservice(Addonservice addonservice, Reservationroomdetails reservationroomdetails,
			Date createday, double price, int quantity, double amount, int paymentstt) {
		this.addonservice = addonservice;
		this.reservationroomdetails = reservationroomdetails;
		this.createday = createday;
		this.price = price;
		this.quantity = quantity;
		this.amount = amount;
		this.paymentstt = paymentstt;
	}

	public Reservationaddonservice(Addonservice addonservice, Reservationroomdetails reservationroomdetails,
			Date createday, double price, int quantity, double amount, Date paymentdate, String paymentchannel,
			int paymentstt) {
		this.addonservice = addonservice;
		this.reservationroomdetails = reservationroomdetails;
		this.createday = createday;
		this.price = price;
		this.quantity = quantity;
		this.amount = amount;
		this.paymentdate = paymentdate;
		this.paymentchannel = paymentchannel;
		this.paymentstt = paymentstt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "reservationaddonserviceid", unique = true, nullable = false)
	public Integer getReservationaddonserviceid() {
		return this.reservationaddonserviceid;
	}

	public void setReservationaddonserviceid(Integer reservationaddonserviceid) {
		this.reservationaddonserviceid = reservationaddonserviceid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "addonserviceid", nullable = false)
	public Addonservice getAddonservice() {
		return this.addonservice;
	}

	public void setAddonservice(Addonservice addonservice) {
		this.addonservice = addonservice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reservationroomdetailsid", nullable = false)
	public Reservationroomdetails getReservationroomdetails() {
		return this.reservationroomdetails;
	}

	public void setReservationroomdetails(Reservationroomdetails reservationroomdetails) {
		this.reservationroomdetails = reservationroomdetails;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createday", nullable = false, length = 10)
	public Date getCreateday() {
		return this.createday;
	}

	public void setCreateday(Date createday) {
		this.createday = createday;
	}

	@Column(name = "price", nullable = false)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "amount", nullable = false)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "paymentdate", length = 10)
	public Date getPaymentdate() {
		return this.paymentdate;
	}

	public void setPaymentdate(Date paymentdate) {
		this.paymentdate = paymentdate;
	}

	@Column(name = "paymentchannel", length = 20)
	public String getPaymentchannel() {
		return this.paymentchannel;
	}

	public void setPaymentchannel(String paymentchannel) {
		this.paymentchannel = paymentchannel;
	}

	@Column(name = "paymentstt", nullable = false)
	public int getPaymentstt() {
		return this.paymentstt;
	}

	public void setPaymentstt(int paymentstt) {
		this.paymentstt = paymentstt;
	}
	
	@Column(name = "latecheckoutid")
	public int getLatecheckoutid() {
		return latecheckoutid;
	}

	public void setLatecheckoutid(int latecheckoutid) {
		this.latecheckoutid = latecheckoutid;
	}

	public Reservationaddonservice(Integer reservationaddonserviceid, Addonservice addonservice,
			Reservationroomdetails reservationroomdetails, Date createday, double price, int quantity, double amount,
			Date paymentdate, String paymentchannel, int latecheckoutid, int paymentstt) {
		super();
		this.reservationaddonserviceid = reservationaddonserviceid;
		this.addonservice = addonservice;
		this.reservationroomdetails = reservationroomdetails;
		this.createday = createday;
		this.price = price;
		this.quantity = quantity;
		this.amount = amount;
		this.paymentdate = paymentdate;
		this.paymentchannel = paymentchannel;
		this.latecheckoutid = latecheckoutid;
		this.paymentstt = paymentstt;
	}

	@Override
	public String toString() {
		return "Reservationaddonservice [reservationaddonserviceid=" + reservationaddonserviceid + ", addonservice="
				+ addonservice + ", reservationroomdetails=" + reservationroomdetails + ", createday=" + createday
				+ ", price=" + price + ", quantity=" + quantity + ", amount=" + amount + ", paymentdate=" + paymentdate
				+ ", paymentchannel=" + paymentchannel + ", latecheckoutid=" + latecheckoutid + ", paymentstt="
				+ paymentstt + "]";
	}
	

}
