package com.demo.models;
// Generated Dec 6, 2022, 10:46:20 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rooms generated by hbm2java
 */
@Entity
@Table(name = "rooms", catalog = "doanky4")
public class Rooms implements java.io.Serializable {

	private Integer roomid;
	private Roomtype roomtype;
	private String roomname;
	private String roomtypecontent;
	private int extrabed;
	private int hotelroomstatus;
	private Set<Reservationroomdetails> reservationroomdetailses = new HashSet<Reservationroomdetails>(0);

	public Rooms() {
	}

	public Rooms(Roomtype roomtype, String roomname, String roomtypecontent, int extrabed, int hotelroomstatus) {
		this.roomtype = roomtype;
		this.roomname = roomname;
		this.roomtypecontent = roomtypecontent;
		this.extrabed = extrabed;
		this.hotelroomstatus = hotelroomstatus;
	}

	public Rooms(Roomtype roomtype, String roomname, String roomtypecontent, int extrabed, int hotelroomstatus,
			Set<Reservationroomdetails> reservationroomdetailses) {
		this.roomtype = roomtype;
		this.roomname = roomname;
		this.roomtypecontent = roomtypecontent;
		this.extrabed = extrabed;
		this.hotelroomstatus = hotelroomstatus;
		this.reservationroomdetailses = reservationroomdetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "roomid", unique = true, nullable = false)
	public Integer getRoomid() {
		return this.roomid;
	}

	public void setRoomid(Integer roomid) {
		this.roomid = roomid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roomstypeid", nullable = false)
	public Roomtype getRoomtype() {
		return this.roomtype;
	}

	public void setRoomtype(Roomtype roomtype) {
		this.roomtype = roomtype;
	}

	@Column(name = "roomname", nullable = false, length = 50)
	public String getRoomname() {
		return this.roomname;
	}

	public void setRoomname(String roomname) {
		this.roomname = roomname;
	}

	@Column(name = "roomtypecontent", nullable = false, length = 50)
	public String getRoomtypecontent() {
		return this.roomtypecontent;
	}

	public void setRoomtypecontent(String roomtypecontent) {
		this.roomtypecontent = roomtypecontent;
	}

	@Column(name = "extrabed", nullable = false)
	public int getExtrabed() {
		return this.extrabed;
	}

	public void setExtrabed(int extrabed) {
		this.extrabed = extrabed;
	}

	@Column(name = "hotelroomstatus", nullable = false)
	public int getHotelroomstatus() {
		return this.hotelroomstatus;
	}

	public void setHotelroomstatus(int hotelroomstatus) {
		this.hotelroomstatus = hotelroomstatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rooms")
	public Set<Reservationroomdetails> getReservationroomdetailses() {
		return this.reservationroomdetailses;
	}

	public void setReservationroomdetailses(Set<Reservationroomdetails> reservationroomdetailses) {
		this.reservationroomdetailses = reservationroomdetailses;
	}

}
