package com.demo.models;
// Generated Dec 6, 2022, 10:46:20 AM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Roomtypeimage generated by hbm2java
 */
@Entity
@Table(name = "roomtypeimage", catalog = "doanky4")
public class Roomtypeimage implements java.io.Serializable {

	private Integer roomtypeimageid;
	private Roomtype roomtype;
	private String roomtypeimagename;

	public Roomtypeimage() {
	}

	public Roomtypeimage(Roomtype roomtype, String roomtypeimagename) {
		this.roomtype = roomtype;
		this.roomtypeimagename = roomtypeimagename;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "roomtypeimageid", unique = true, nullable = false)
	public Integer getRoomtypeimageid() {
		return this.roomtypeimageid;
	}

	public void setRoomtypeimageid(Integer roomtypeimageid) {
		this.roomtypeimageid = roomtypeimageid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roomstypeid", nullable = false)
	public Roomtype getRoomtype() {
		return this.roomtype;
	}

	public void setRoomtype(Roomtype roomtype) {
		this.roomtype = roomtype;
	}

	@Column(name = "roomtypeimagename", nullable = false, length = 50)
	public String getRoomtypeimagename() {
		return this.roomtypeimagename;
	}

	public void setRoomtypeimagename(String roomtypeimagename) {
		this.roomtypeimagename = roomtypeimagename;
	}

}
