package com.demo.models;
// Generated Dec 6, 2022, 10:46:20 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roomtype generated by hbm2java
 */
@Entity
@Table(name = "roomtype", catalog = "doanky4")
public class Roomtype implements java.io.Serializable {

	private Integer roomstypeid;
	private Hotel hotel;
	private String roomstypename;
	private int numcusdefault;
	private int maxcus;
	private String views;
	private String description;
	private int minibar;
	private int smoking;
	private int breakfast;
	private int shower;
	private int roomsize;
	private int roomtypestt;
	private int publicprice;
	private int netprice;
	private Set<Contractinforoomtype> contractinforoomtypes = new HashSet<Contractinforoomtype>(0);
	private Set<Roomtypeimage> roomtypeimages = new HashSet<Roomtypeimage>(0);
	private Set<Policies> policieses = new HashSet<Policies>(0);
	private Set<Rooms> roomses = new HashSet<Rooms>(0);
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Roomtype() {
	}

	public Roomtype(Hotel hotel, String roomstypename, int numcusdefault, int maxcus, String views, String description,
			int minibar, int smoking, int breakfast, int shower, int roomsize, int roomtypestt, int publicprice,
			int netprice) {
		this.hotel = hotel;
		this.roomstypename = roomstypename;
		this.numcusdefault = numcusdefault;
		this.maxcus = maxcus;
		this.views = views;
		this.description = description;
		this.minibar = minibar;
		this.smoking = smoking;
		this.breakfast = breakfast;
		this.shower = shower;
		this.roomsize = roomsize;
		this.roomtypestt = roomtypestt;
		this.publicprice = publicprice;
		this.netprice = netprice;
	}

	public Roomtype(Hotel hotel, String roomstypename, int numcusdefault, int maxcus, String views, String description,
			int minibar, int smoking, int breakfast, int shower, int roomsize, int roomtypestt, int publicprice,
			int netprice, Set<Contractinforoomtype> contractinforoomtypes, Set<Roomtypeimage> roomtypeimages,
			Set<Policies> policieses, Set<Rooms> roomses, Set<Reservation> reservations) {
		this.hotel = hotel;
		this.roomstypename = roomstypename;
		this.numcusdefault = numcusdefault;
		this.maxcus = maxcus;
		this.views = views;
		this.description = description;
		this.minibar = minibar;
		this.smoking = smoking;
		this.breakfast = breakfast;
		this.shower = shower;
		this.roomsize = roomsize;
		this.roomtypestt = roomtypestt;
		this.publicprice = publicprice;
		this.netprice = netprice;
		this.contractinforoomtypes = contractinforoomtypes;
		this.roomtypeimages = roomtypeimages;
		this.policieses = policieses;
		this.roomses = roomses;
		this.reservations = reservations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "roomstypeid", unique = true, nullable = false)
	public Integer getRoomstypeid() {
		return this.roomstypeid;
	}

	public void setRoomstypeid(Integer roomstypeid) {
		this.roomstypeid = roomstypeid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hotelid", nullable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "roomstypename", nullable = false, length = 50)
	public String getRoomstypename() {
		return this.roomstypename;
	}

	public void setRoomstypename(String roomstypename) {
		this.roomstypename = roomstypename;
	}

	@Column(name = "numcusdefault", nullable = false)
	public int getNumcusdefault() {
		return this.numcusdefault;
	}

	public void setNumcusdefault(int numcusdefault) {
		this.numcusdefault = numcusdefault;
	}

	@Column(name = "maxcus", nullable = false)
	public int getMaxcus() {
		return this.maxcus;
	}

	public void setMaxcus(int maxcus) {
		this.maxcus = maxcus;
	}

	@Column(name = "views", nullable = false, length = 50)
	public String getViews() {
		return this.views;
	}

	public void setViews(String views) {
		this.views = views;
	}

	@Column(name = "description", nullable = false, length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "minibar", nullable = false)
	public int getMinibar() {
		return this.minibar;
	}

	public void setMinibar(int minibar) {
		this.minibar = minibar;
	}

	@Column(name = "smoking", nullable = false)
	public int getSmoking() {
		return this.smoking;
	}

	public void setSmoking(int smoking) {
		this.smoking = smoking;
	}

	@Column(name = "breakfast", nullable = false)
	public int getBreakfast() {
		return this.breakfast;
	}

	public void setBreakfast(int breakfast) {
		this.breakfast = breakfast;
	}

	@Column(name = "shower", nullable = false)
	public int getShower() {
		return this.shower;
	}

	public void setShower(int shower) {
		this.shower = shower;
	}

	@Column(name = "roomsize", nullable = false)
	public int getRoomsize() {
		return this.roomsize;
	}

	public void setRoomsize(int roomsize) {
		this.roomsize = roomsize;
	}

	@Column(name = "roomtypestt", nullable = false)
	public int getRoomtypestt() {
		return this.roomtypestt;
	}

	public void setRoomtypestt(int roomtypestt) {
		this.roomtypestt = roomtypestt;
	}

	@Column(name = "publicprice", nullable = false)
	public int getPublicprice() {
		return this.publicprice;
	}

	public void setPublicprice(int publicprice) {
		this.publicprice = publicprice;
	}

	@Column(name = "netprice", nullable = false)
	public int getNetprice() {
		return this.netprice;
	}

	public void setNetprice(int netprice) {
		this.netprice = netprice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roomtype")
	public Set<Contractinforoomtype> getContractinforoomtypes() {
		return this.contractinforoomtypes;
	}

	public void setContractinforoomtypes(Set<Contractinforoomtype> contractinforoomtypes) {
		this.contractinforoomtypes = contractinforoomtypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roomtype")
	public Set<Roomtypeimage> getRoomtypeimages() {
		return this.roomtypeimages;
	}

	public void setRoomtypeimages(Set<Roomtypeimage> roomtypeimages) {
		this.roomtypeimages = roomtypeimages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roomtype")
	public Set<Policies> getPolicieses() {
		return this.policieses;
	}

	public void setPolicieses(Set<Policies> policieses) {
		this.policieses = policieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roomtype")
	public Set<Rooms> getRoomses() {
		return this.roomses;
	}

	public void setRoomses(Set<Rooms> roomses) {
		this.roomses = roomses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roomtype")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
