package com.demo.models;
// Generated Dec 6, 2022, 10:46:20 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ward generated by hbm2java
 */
@Entity
@Table(name = "ward", catalog = "doanky4")
public class Ward implements java.io.Serializable {

	private int wardid;
	private City city;
	private String wardname;
	private Set<Hotel> hotels = new HashSet<Hotel>(0);

	public Ward() {
	}

	public Ward(int wardid, City city, String wardname) {
		this.wardid = wardid;
		this.city = city;
		this.wardname = wardname;
	}

	public Ward(int wardid, City city, String wardname, Set<Hotel> hotels) {
		this.wardid = wardid;
		this.city = city;
		this.wardname = wardname;
		this.hotels = hotels;
	}

	@Id

	@Column(name = "wardid", unique = true, nullable = false)
	public int getWardid() {
		return this.wardid;
	}

	public void setWardid(int wardid) {
		this.wardid = wardid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cityid", nullable = false)
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@Column(name = "wardname", nullable = false, length = 30)
	public String getWardname() {
		return this.wardname;
	}

	public void setWardname(String wardname) {
		this.wardname = wardname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ward")
	public Set<Hotel> getHotels() {
		return this.hotels;
	}

	public void setHotels(Set<Hotel> hotels) {
		this.hotels = hotels;
	}

}
