package com.demo.models;
// Generated Nov 29, 2022, 9:55:34 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Addonservice generated by hbm2java
 */

public class XuanAddonservice implements java.io.Serializable {

	private Integer addonserviceid;
	private String addonservicename;
	private double price;
	
	public XuanAddonservice() {
	}

	public Integer getAddonserviceid() {
		return addonserviceid;
	}

	public void setAddonserviceid(Integer addonserviceid) {
		this.addonserviceid = addonserviceid;
	}

	public String getAddonservicename() {
		return addonservicename;
	}

	public void setAddonservicename(String addonservicename) {
		this.addonservicename = addonservicename;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public XuanAddonservice(Integer addonserviceid, String addonservicename, double price) {
		super();
		this.addonserviceid = addonserviceid;
		this.addonservicename = addonservicename;
		this.price = price;
	}

	

}
